version: 01.00.00

server:
   port: ${SERVER_PORT}

generator:
   name-host: ${NAME_HOST}
   name-PORT: ${NAME_PORT}
   cidade-host: ${CIDADE_HOST}
   cidade-PORT: ${CIDADE_PORT}

spring:
   application:
     name: gerador-nome


#management.endpoints.web.exposure.include: prometheus, metrics, info, health
management:
   server:
      port: 9090
   endpoints:
      web:
         base-path: "/"
         path-mapping:
            prometheus: "metrics"
         exposure:
            include: "health, prometheus, info, metrics"
   metrics:
      export:
         prometheus:
            enabled: true
      endpoint:
         metrics:
            enabled: false
         prometheus:
            enabled: true